# Deployment DB
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-db
spec:
  selector:
    matchLabels:
      app: mongo-db
  template:
    metadata:
      labels:
        app: mongo-db
    spec:
      containers:
        - name: mongo-db
          image: mongo:4.4.6
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "db-username"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "db-password"
          ports:
            - containerPort: 27017

---
# Service DB
apiVersion: v1
kind: Service
metadata: 
  name: mongo-db
spec:
  selector:
    app: mongo-db
  ports:
    - port: 27017
  type: ClusterIP
